version: '2'
services:
    predictimo-app:
        image: predictimo
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://predictimo-postgresql:5432/Predictimo
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    predictimo-postgresql:
        extends:
            file: postgresql.yml
            service: predictimo-postgresql
